theme: jekyll-theme-minimal
title: UFRGS/INF - COVID-19
description: COVID-19 projects developed by researchers at the Instituto de Informática of the Federal University of Rio Grande do Sul (Brazil).
